import { AUTHENTICITY_TYPES, AUTHENTICITY_TRANSLATIONS } from 'var/authenticityTypes'

export const AUTHENTICITY_TYPE_SELECT_ITEMS = [
  { value: '' },
  { value: AUTHENTICITY_TYPES.PASSED, label: AUTHENTICITY_TRANSLATIONS[AUTHENTICITY_TYPES.PASSED] },
  { value: AUTHENTICITY_TYPES.FAILED, label: AUTHENTICITY_TRANSLATIONS[AUTHENTICITY_TYPES.FAILED] },
  { value: AUTHENTICITY_TYPES.INDECISIVE, label: AUTHENTICITY_TRANSLATIONS[AUTHENTICITY_TYPES.INDECISIVE] }, // eslint-disable-line max-len
]

export default AUTHENTICITY_TYPE_SELECT_ITEMS
